project_projects:
    resource: "@ProjectBundle/Resources/config/routing/project.yml"
    prefix:   /projects

project_homepage:
    path:     /
    defaults: { _controller: ProjectBundle:Default:index }

project_hello:
    path:     /hello/{name}
    defaults: { _controller: ProjectBundle:Default:hello }
